# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  uiSource : 'authentification'
  uiBuild : $(uiSource)/build

trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: Bash@3
  inputs:
    targetType: 'inline'
- script:
  displayName: 'npm install and npm run build'
  workingDirectory: '$(Build.SourcesDirectory)/authentification'
  
- script: 
    echo '-----------cd--------------'
    ls -ltr
    cd myProject-azure-fil-rouge
    echo 'inside myProject-azure-fil-rouge'
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo '--------------cd-------------'
      ls
      echo '--------------Build.BinariesDirectory-------------'
      echo $(Build.BinariesDirectory)
      ls
      cd authentification
      echo 'inside authentification'
      ls
      cd build
      echo 'inside build'
      ls
      echo '--------------Build.SourcesDirectory-------------'
      echo $(Build.SourcesDirectory)
      ls
      cd authentification
      echo 'inside authentification------'
      ls
      echo 'inside build'
      cd build
      echo '--------------Build.ArtifactStagingDirectory-------------'
      echo $(Build.ArtifactStagingDirectory)
      ls
      cd authentification
      echo 'inside authentification'
      ls

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(uiBuild)'
#    includeRootFolder: false
#    archiveType: 'zip'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/authentification/$(Build.BuildId).zip'
#    replaceExistingArchive: true
#- task: PublishBuildArtifacts@1
#  inputs:
#      PathtoPublish: '$(Build.ArtifactStagingDirectory)/authentification'


