# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'service-connection-azure-farouk'
    appType: 'webAppLinux'
    WebAppName: 'react-dashboard-front-farouk'
    packageForLinux: '$(System.DefaultWorkingDirectory)/client/build'
    RuntimeStack: 'NODE|16-lts'
    StartupCommand: 'npm start'

